name: Generate Snake Animation

# Este cron ejecuta el workflow cada 2 semanas
on:
  schedule:
    # Ejecuta el workflow cada dos semanas (domingo a la medianoche UTC)
    - cron: "0 0 * * 0/14"

  # También se puede ejecutar manualmente
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Chequear el repositorio
      - uses: actions/checkout@v3

      # Paso 2: Generar el archivo snake.svg con Platane/snk
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      # Paso 3: Subir el archivo snake.svg a la rama actual
      - name: Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated snake animation"
          add: dist/snake.svg
          author_name: "github-actions"       # Cambiamos el autor
          author_email: "actions@github.com"  # Cambiamos el correo Estos dos con el fin de que no refleje commits en mi historial
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
